Class Scan.CheckRelationResponse Extends Ens.Response [ ClassType = persistent ]
{

Property IsRelated As %Boolean;

Storage Default
{
<Data name="CheckRelationResponseDefaultData">
<Subscript>"CheckRelationResponse"</Subscript>
<Value name="1">
<Value>IsRelated</Value>
</Value>
</Data>
<DefaultData>CheckRelationResponseDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
